version: '3.8'
services:

  nest-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api-1
    expose:
      - 3000
    ports:
      - '3011:3000'
    networks:
        public_net:
            ipv4_address: 192.168.0.11
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.docker
    environment:
      - PORT=3000

  nest-api-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api-2
    expose:
      - 3000
    ports:
      - '3022:3000'
    networks:
        public_net:
            ipv4_address: 192.168.0.22
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.docker
    environment:
      - PORT=3000

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=smilepay
      - POSTGRES_PASSWORD=smilepay
      - POSTGRES_DB=smilepay
    expose:
      - 5432
    networks:
        public_net:
            ipv4_address: 192.168.0.55
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    networks:
        public_net:
            ipv4_address: 192.168.0.66
    ports:
      - '6378:6379'

  haproxy:
      image: haproxy:1.7
      container_name: haproxy
      ports:
          - 8080:8080
      expose:
          - 8080
      volumes:
          - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      depends_on:
        - nest-api-1
        - nest-api-2
      networks:
          public_net:
              ipv4_address: 192.168.0.33
      environment:
          - NEST_1_IP=192.168.0.11
          - NEST_2_IP=192.168.0.22
          - NEST_EXPOSED_PORT=3000

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nest-api-1
      - nest-api-2
      - haproxy

  # locust:
  #   image: locustio/locust
  #   container_name: locust
  #   ports:
  #     - '8089:8089'
  #   volumes:
  #     - ./locust/locustfile.py:/mnt/locust/locustfile.py
  #   depends_on:
  #     - nest-api-1
  #     - nest-api-2
  #     - haproxy

volumes:
  postgres:

networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24
