version: '3.8'
services:

  nest-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api-1
    ports:
      - '3008:3000'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.docker
    environment:
      - PORT=3000

  nest-api-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api-2
    ports:
      - '3009:3000'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.docker
    environment:
      - PORT=3000

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=smilepay
      - POSTGRES_PASSWORD=smilepay
      - POSTGRES_DB=smilepay
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis
    container_name: redis
    ports:
      - '6378:6379'

  haproxy:
      image: haproxy:1.7
      container_name: haproxy
      ports:
          - 8080:80
      expose:
          - 8080
      volumes:
          - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      depends_on:
        - nest-api-1
        - nest-api-2
      networks:
          public_net:
              ipv4_address: 192.168.0.33
      environment:
          - NEST_1_IP=192.168.0.11
          - NEST_2_IP=192.168.0.22
          - NEST_EXPOSED_PORT=3000

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nest-api-1
      - nest-api-2
      - haproxy

volumes:
  postgres:

networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24
