version: '3.8'
services:

  api_service:
    build: .
    environment:
      - DB_USER=smilepay
      - DB_PASSWORD=smilepay
      - DB_NAME=smilepay
      - DB_HOST=postgres
      - DB_PORT=5432
      - DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=smilepay
      - POSTGRES_PASSWORD=smilepay
      - POSTGRES_DB=smilepay
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'

  haproxy:
      image: haproxy:1.7
      ports:
          - 80:80
      expose:
          - 80
      volumes:
          - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      environment:
          - smilePay_serviceOne=localhost
          - smilePay_serviceTwo=localhost
          - smilePay_PORT=8080
      depends_on:
        - api_service

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    container_name: reverse-proxy
    depends_on:
      - api_service

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api_service

volumes:
  postgres:
