---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "Install Node.js 13"
  become: true
  shell: |
    # Install Node.js LTS version as our base Node.js version
    sudo apt install nodejs npm -y
    # Use n version manager to use Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0
    hash -r

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes