version: '3.8'
services:

  locust:
    image: locustio/locust
    container_name: locust
    restart: unless-stopped
    ports:
      - '8089:8089'
    volumes:
      - ./locust/locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --host=http://haproxy:8080/api
    networks:
      - load_testing_network

networks:
  load_testing_network: