version: '3.8'
services:

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "7070:8080"
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      - application_network

volumes:
  jenkins:

networks:
  application_network: